name: StrikeSync
version: '${project.version}'
main: me.vexmc.strikesync.StrikeSyncPlugin
api-version: '1.20'
load: STARTUP
depend: [ProtocolLib]
authors: [owengregson]
description: Asynchronous hit registration and knockback for modern Minecraft.
website: https://github.com/owengregson/StrikeSync
commands:
  strikesync:
    description: Main command for the StrikeSync plugin
    aliases: [ss]
    usage: /ss help
    permission: strikesync.command.use